"""add bilingual _en columns to projects and experiences

Revision ID: 73f0ecb5b134
Revises: f1fdb62a4e01
Create Date: 2026-05-28 18:12:39.400664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73f0ecb5b134'
down_revision: Union[str, Sequence[str], None] = 'f1fdb62a4e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_en', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('location_en', sa.String(length=200), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content_en', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('content_en')
        batch_op.drop_column('description_en')
        batch_op.drop_column('title_en')

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_column('location_en')
        batch_op.drop_column('description_en')
        batch_op.drop_column('role_en')

    # ### end Alembic commands ###
